---
# Source: aws-ebs-csi-driver/templates/controller-poddisruptionbudget.yaml
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: ebs-csi-controller-pod-disruption-budget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ebs-csi-controller
