---
# Source: aws-ebs-csi-driver/templates/poddisruptionbudget-snapshot-controller.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ebs-snapshot-controller
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
spec:
  selector:
    matchLabels:
      app: ebs-snapshot-controller
      app.kubernetes.io/name: aws-ebs-csi-driver
  maxUnavailable: 1
