---
# Source: aws-ebs-csi-driver/templates/rolebinding-leases.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-csi-leases-rolebinding
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
subjects:
- kind: ServiceAccount
  name: ebs-csi-controller-sa
roleRef:
  kind: Role
  name: ebs-csi-leases-role
  apiGroup: rbac.authorization.k8s.io
