timeout: 1800s
steps:
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud:v20200421-a2bf5f8
    entrypoint: ./hack/prow.sh
    env:
      - GIT_TAG=${_GIT_TAG}
      - PULL_BASE_REF=${_PULL_BASE_REF}
      - REGISTRY_NAME=gcr.io/${_STAGING_PROJECT}
      - HOME=/root
substitutions:
  _STAGING_PROJECT: "k8s-staging-provider-aws"
