timeout: 3600s
steps:
  - name: gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20220506-774f302a94
    entrypoint: ./hack/prow.sh
    env:
      - GIT_TAG=${_GIT_TAG}
      - PULL_BASE_REF=${_PULL_BASE_REF}
      - REGISTRY_NAME=gcr.io/${_STAGING_PROJECT}
      - HOME=/root
substitutions:
  _STAGING_PROJECT: "k8s-staging-provider-aws"
