apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- controller_add_snapshotter.yaml
- controller_add_resizer.yaml
resources:
- rbac_add_snapshotter.yaml
- rbac_add_resizer.yaml
- rbac_add_snapshot_controller.yaml
- snapshot_controller.yaml
