---
# Source: aws-ebs-csi-driver/templates/rolebinding-snapshot-controller-leaderelection.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-snapshot-controller-leaderelection
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
subjects:
  - kind: ServiceAccount
    name: ebs-snapshot-controller
    namespace: default
roleRef:
  kind: Role
  name: ebs-snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io
