---
# Source: aws-ebs-csi-driver/templates/serviceaccount-snapshot-controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
