#!/bin/bash
# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### This script helps setup, run, and cleanup an ebs-scale-test. See README.md
set -euo pipefail
BASE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

## Overridable environment variables. See README.md
export CLUSTER_TYPE
export TEST_TYPE
export REPLICAS
export DRIVER_VALUES_FILEPATH

export CLUSTER_NAME
export EXPORT_DIR
export S3_BUCKET
export SCALABILITY_TEST_RUN_NAME

CLUSTER_TYPE=${CLUSTER_TYPE:="pre-allocated"}
TEST_TYPE=${TEST_TYPE:="scale-sts"}
REPLICAS=${REPLICAS:=1000}
DRIVER_VALUES_FILEPATH=${DRIVER_VALUES_FILEPATH:="$BASE_DIR/helpers/cluster-setup/scale-driver-values.yaml"}
# TODO Q: Does anyone need an $OVERRIDE_KUBECONFIG? Let's discuss.

CLUSTER_NAME=${CLUSTER_NAME:="ebs-scale-$CLUSTER_TYPE"}
EXPORT_DIR=${EXPORT_DIR:=$(mktemp -d)}
S3_BUCKET=${S3_BUCKET:="ebs-scale-tests"}
SCALABILITY_TEST_RUN_NAME=${SCALABILITY_TEST_RUN_NAME:="$CLUSTER_NAME-$TEST_TYPE-$REPLICAS-$(date -u +%Y-%m-%dT%H:%M%Z)"}

## Script helpers and internal environment variables
export PRE_ALLOCATED_NODES K8S_VERSION AWS_ACCOUNT_ID AWS_REGION BASE_DIR TEMPOUT

PRE_ALLOCATED_NODES=${PRE_ALLOCATED_NODES:=$((($REPLICAS / 100) + 1))}
K8S_VERSION=$(aws eks describe-cluster-versions --query "clusterVersions[0].clusterVersion")

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region)
TEMPOUT=$(mktemp)

source "${BASE_DIR}/helpers/cluster-setup/manage-cluster.sh"
source "${BASE_DIR}/helpers/scale-test/export-to-s3.sh"
source "${BASE_DIR}/helpers/scale-test//scale-sts-test/scale-sts.sh"

usage() {
  echo "Usage: $0 [base-cmd]"
  echo "Possible base-cmds: 'setup', 'run', 'cleanup'"
  exit 1
}

# TODO Q: I'm open to relying on `make tools` /bin dependencies. But that might be confusing to those just wanting to run scale tests.
check_dependencies_helper() {
  local readonly dependencies=("kubectl" "aws" "eksctl" "gomplate")

  for cmd in "${dependencies[@]}"; do
    if ! command -v "${cmd}" &>/dev/null; then
      echo "${cmd} could not be found, please install it."
      exit 1
    fi
  done
}

## Script start

# Functions sourced from helpers/cluster-setup/manage-cluster.sh
setup-scale() {
  create_cluster
  deploy_ebs_csi_driver
}

# Functions sourced from helpers/scale-test/...
run-scale() {
  # TODO Q: Is it worth restarting EBS CSI Controller pod to ensure clean metrics/logs? Or move EBS CSI Driver install/cleanup to 'run' instead of 'setup'? Let's discuss.
  aws eks update-kubeconfig --name "$CLUSTER_NAME"
  sts_scale_test
  export_to_s3
}

# Functions sourced from helpers/cluster-setup/manage-cluster.sh
clean-scale() {
  cleanup_cluster
}

main() {
  # Check params
  [[ $# -ne 1 ]] && usage
  check_dependencies_helper

  case "$1" in
  *setup* | *create*) setup-scale ;;
  *run*) run-scale ;;
  *clean*) clean-scale ;;
  *) usage ;;
  esac
}

main "$@"
