---
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: ebs-csi-controller-pod-disruption-budget
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ebs-csi-controller
