{{- if and .Values.enableVolumeSnapshot (ne (.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1") true) }}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}
{{- end }}
