{{- if and .Values.controller.enableMetrics (not .Values.nodeComponentOnly) -}}
{{/* Metrics for the controller pods - we create a separate service per container
because the prometheus.io annotations don't allow specifying multiple ports */}}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller"
  "TargetPod" "ebs-csi-controller"
  "Port" 3301
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-provisioner"
  "TargetPod" "ebs-csi-controller"
  "Port" 3302
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-attacher"
  "TargetPod" "ebs-csi-controller"
  "Port" 3303
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-resizer"
  "TargetPod" "ebs-csi-controller"
  "Port" 3304
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-liveness-probe"
  "TargetPod" "ebs-csi-controller"
  "Port" 3305
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- if or .Values.sidecars.snapshotter.forceEnable (.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1beta1") (.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1") }}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-snapshotter"
  "TargetPod" "ebs-csi-controller"
  "Port" 3306
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- end }}
{{- if (.Values.controller.volumeModificationFeature).enabled }}
{{- include "metrics" (dict
  "Name" "ebs-csi-controller-volumemodifier"
  "TargetPod" "ebs-csi-controller"
  "Port" 3307
  "ServiceMonitor" .Values.controller.serviceMonitor
  "EnableAnnotations" .Values.controller.enablePrometheusAnnotations
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- end }}
{{- end }}
{{- if .Values.node.enableMetrics }}
{{- include "metrics" (dict
  "Name" "ebs-csi-node"
  "TargetPod" "ebs-csi-node"
  "Port" 3302
  "ServiceMonitor" .Values.node.serviceMonitor
  "EnableAnnotations" .Values.node.enablePrometheusAnnotations
  "InternalTrafficPolicy" "Local"
  "Release" .Release "Capabilities" .Capabilities) -}}
{{- end }}
