{{- if .Values.enableVolumeSnapshot }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ebs-snapshot-controller
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ebs-snapshot-controller
      {{- include "aws-ebs-csi-driver.selectorLabels" . | nindent 6 }}
  maxUnavailable: 1
{{- end }}
