{{- if .Values.enableVolumeSnapshot }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-snapshot-controller-leaderelection
  namespace: kube-system
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.snapshot.name }}
    namespace: kube-system
roleRef:
  kind: Role
  name: ebs-snapshot-controller-leaderelection
  apiGroup: rbac.authorization.k8s.io

{{- end }}
