{{- if and .Values.controller.serviceAccount.create (not .Values.nodeComponentOnly) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- $annotations := dict }}
    {{- range $key, $value := . }}
    {{- $valueString := ternary "" (toString $value) (kindIs "invalid" $value) }}
    {{- $_ := set $annotations (tpl $key $) (tpl $valueString $) }}
    {{- end }}
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- if .Values.controller.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.controller.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end -}}
