{{- if .Values.enableVolumeSnapshot }}
#Snapshot controller
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  serviceName: ebs-snapshot-controller
  replicas: 1
  selector:
    matchLabels:
      app: ebs-snapshot-controller
      {{- include "aws-ebs-csi-driver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: ebs-snapshot-controller
        {{- include "aws-ebs-csi-driver.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.snapshot.name }}
      containers:
        - name: snapshot-controller
          image: k8s.gcr.io/sig-storage/snapshot-controller:v3.0.3
          args:
            - --v=5
            - --leader-election=false
{{- end }}
