{{- range .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
  {{- if .annotations }}
  annotations: {{- .annotations | toYaml | trim | nindent 4 }}
  {{- end }}
  {{- if .labels }}
  labels: {{- .labels | toYaml | trim | nindent 4 }}
  {{- end }}
provisioner: ebs.csi.aws.com
{{ omit (dict "volumeBindingMode" "WaitForFirstConsumer" | merge .) "name" "annotations" "labels" | toYaml }}
{{- end }}
