# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ebs-scale-test
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["6"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ebs-scale-test
      expireAfter: 720h
      startupTaints:
        - key: ebs.csi.aws.com/agent-not-ready
          effect: NoExecute
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 20m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ebs-scale-test
spec:
  role: "KarpenterNodeRole-{{ .Env.CLUSTER_NAME }}"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Env.CLUSTER_NAME }}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "{{ .Env.CLUSTER_NAME }}"
  amiSelectorTerms:
    - alias: al2023@latest
  metadataOptions:
    httpPutResponseHopLimit: 2
