# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values.yaml for ebs-scale-test installation of aws-ebs-csi-driver
image:
  pullPolicy: Always
controller:
  logLevel: 7
  # Having one controller simplifies metrics collection and helps track restarts
  replicaCount: 1
  enableMetrics: true
sidecars:
  provisioner:
    additionalArgs: ["--http-endpoint=:8081"]
  resizer:
    additionalArgs: ["--http-endpoint=:8082"]
  attacher:
    additionalArgs: ["--http-endpoint=:8084"]
