apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: static-snapshot-demo
  namespace: default 
spec:
  snapshotClassName: csi-aws-vsc 
  snapshotContentName: static-snapshot-content
