apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  namespace: kube-system
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-snapshot-controller
  namespace: kube-system
  {{- with .Values.serviceAccount.snapshot.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
